name: "06-05 - Package Pogoda Info Python"
run-name: 06-05 - Package Pogoda Info Python dla ${{ inputs.city }}

on:
  workflow_dispatch:
    inputs:
      city:
        description: "City to get weather info for"
        type: string
        default: "Warsaw"
      release_tag:
        description: "Tag / wersja releasu (np. v1.0.0)"
        default: "v0.1.0"

permissions:
  contents: write

env:
  MY_KEY: '7cff9972d5c98a9a47ddf6a59cb34d8e'

jobs:
  pogoda-info:
    name: obierz informacje o pogodzie + build binarki
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./cwiczenia/pogoda_python
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          python-version: '3.12'
      - name: Instalacja zaleznosci
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Budowanie binarki przy uzyciu PyInstaller
        run: |
          pyinstaller --onefile start.py --name pogoda
      - name: Uruchomienie binarki i zapis do Step Summary
        run: |
          ./dist/pogoda "${{ inputs.city }}" "${{ env.MY_KEY }}" >> "$GITHUB_STEP_SUMMARY"
      - name: Wgranie binarki
        uses: actions/upload-artifact@v4
        with:
          name: pogoda-linux-amd64
          path: ./cwiczenia/pogoda-dist/pogoda
      - name: "Pogoda binary ${{ inputs.release_tag }}"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release_tag }}
          name: "Pogoda binary ${{ inputs.release_tag }}"
          draft: false
          prerelease: false
          files: |
            ./cwiczenia/pogoda_python/dist/pogoda
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
